crafting items: [ENCHANTMENT_TABLE, GOLDEN_APPLE, DIAMOND_SWORD, DIAMOND_HELMET, DIAMOND_CHESTPLATE, DIAMOND_LEGGINGS, DIAMOND_BOOTS, ANVIL]
digging blocks: [GOLD_ORE, DIAMOND_ORE, LAPIS_ORE, OBSIDIAN]
eating items: [GOLDEN_APPLE]
max vein size: 30
store vein ticks: 400